#!/usr/bin/python

import sys
from damaris.gui.DamarisGUI import DamarisGUI

if __name__=="__main__":

    # find scripts to load in parameter list
    exp_script = None
    res_script = None
    if len(sys.argv)<=3:
        if len(sys.argv)>=2:
            exp_script=sys.argv[1]
        if len(sys.argv)==3:
            res_script=sys.argv[2]
    else:
        print """too many arguments.\nDamarisGUI.py (Experiment File|"") (Result File|"")"""
    
    d=DamarisGUI(exp_script, res_script)
    d.run()
    sys.stdout=sys.__stdout__
    sys.stderr=sys.__stderr__
