#!/usr/bin/python

import sys
import damaris.gui.DamarisGUI
import matplotlib

# argv is already parsed by gtk initialisation
myargs=sys.argv[1:]
myname=sys.argv[0]

# find debug flag:
if "--debug" in myargs:
    damaris.gui.DamarisGUI.debug = True
    print "debug flag set"
    try:
        import resource
        resource.setrlimit(resource.RLIMIT_CORE, (-1,-1))
    except ImportError:
        pass

    myargs.remove("--debug")

# remove matplotlib flags
if "-d"+matplotlib.rcParams["backend"] in myargs:
    myargs.remove("-d"+matplotlib.rcParams["backend"])

# find scripts to load in parameter list
exp_script = None
res_script = None
if len(myargs)<=2:
    if len(myargs)>=1:
        exp_script=myargs[0]
    if len(myargs)==2:
        res_script=myargs[1]
else:
    print """too many arguments.\n%s [--debug] [-dGTK(Agg|Cairo|)] (Experiment File|"") (Result File|"")"""%(myname)
    
d=damaris.gui.DamarisGUI.DamarisGUI(exp_script, res_script)
d.run()
sys.stdout=sys.__stdout__
sys.stderr=sys.__stderr__
